# Use the latest Node.js Alpine image
FROM node:${nodeVersion}

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy source code
COPY . .

# Expose the port the app runs on
EXPOSE ${port}

# Define the command to run the application
CMD ["npm", "start"]